/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database1;

import java.sql.*;

/**
 *
 * @author user
 */
public class date extends javax.swing.JFrame {

    Connection myconObj = null;
    Statement mystatObj = null;
    ResultSet myResObj = null;
    ResultSetMetaData myMeta = null;

    /**
     * Creates new form date
     */
    public date() {
        initComponents();
        try {
            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");
            PreparedStatement preparedStatement = myconObj.prepareStatement("SELECT * FROM JP.DOCTORSCHEDULES WHERE ID = ?");

            preparedStatement.setString(1, doctor.getID());
            myResObj = preparedStatement.executeQuery();

            if (myResObj.next()) {
                ST.setText(myResObj.getString("SUN_TIME"));
                SP.setText(myResObj.getString("SUN_PLACE"));
                MT.setText(myResObj.getString("MON_TIME"));
                MP.setText(myResObj.getString("MON_PLACE"));
                TUT.setText(myResObj.getString("TUES_TIME"));
                TUP.setText(myResObj.getString("TUES_PLACE"));
                WT.setText(myResObj.getString("WED_TIME"));
                WP.setText(myResObj.getString("WED_PLACE"));
                THT.setText(myResObj.getString("THRUS_TIME"));
                THP.setText(myResObj.getString("THRUS_PLACE"));
                FRT.setText(myResObj.getString("FRI_TIME"));
                FRP.setText(myResObj.getString("FRI_PLACE"));
                SAT.setText(myResObj.getString("SAT_TIME"));
                SAP.setText(myResObj.getString("SAT_PLACE"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ST = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MT = new javax.swing.JTextField();
        TUT = new javax.swing.JTextField();
        WT = new javax.swing.JTextField();
        THT = new javax.swing.JTextField();
        FRT = new javax.swing.JTextField();
        Book1 = new javax.swing.JButton();
        Book2 = new javax.swing.JButton();
        Book3 = new javax.swing.JButton();
        Book4 = new javax.swing.JButton();
        Book5 = new javax.swing.JButton();
        Book6 = new javax.swing.JButton();
        SP = new javax.swing.JTextField();
        MP = new javax.swing.JTextField();
        TUP = new javax.swing.JTextField();
        WP = new javax.swing.JTextField();
        THP = new javax.swing.JTextField();
        FRP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SAT = new javax.swing.JTextField();
        SAP = new javax.swing.JTextField();
        Book7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Sunday");

        jLabel3.setText("Monday");

        ST.setEditable(false);
        ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STActionPerformed(evt);
            }
        });

        jLabel4.setText("Tuesday");

        jLabel5.setText("Wednesday");

        jLabel6.setText("Thursday");

        jLabel7.setText("Friday");

        jLabel8.setText("Time");

        MT.setEditable(false);
        MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTActionPerformed(evt);
            }
        });

        TUT.setEditable(false);
        TUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUTActionPerformed(evt);
            }
        });

        WT.setEditable(false);
        WT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WTActionPerformed(evt);
            }
        });

        THT.setEditable(false);
        THT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THTActionPerformed(evt);
            }
        });

        FRT.setEditable(false);
        FRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRTActionPerformed(evt);
            }
        });

        Book1.setText("Book");
        Book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book1ActionPerformed(evt);
            }
        });

        Book2.setText("Book");
        Book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book2ActionPerformed(evt);
            }
        });

        Book3.setText("Book");
        Book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book3ActionPerformed(evt);
            }
        });

        Book4.setText("Book");
        Book4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book4ActionPerformed(evt);
            }
        });

        Book5.setText("Book");
        Book5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book5ActionPerformed(evt);
            }
        });

        Book6.setText("Book");
        Book6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book6ActionPerformed(evt);
            }
        });

        SP.setEditable(false);
        SP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPActionPerformed(evt);
            }
        });

        MP.setEditable(false);
        MP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPActionPerformed(evt);
            }
        });

        TUP.setEditable(false);
        TUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUPActionPerformed(evt);
            }
        });

        WP.setEditable(false);
        WP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WPActionPerformed(evt);
            }
        });

        THP.setEditable(false);
        THP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THPActionPerformed(evt);
            }
        });

        FRP.setEditable(false);
        FRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRPActionPerformed(evt);
            }
        });

        jLabel9.setText("Place");

        jButton8.setText("back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel11.setText("Saterday");

        SAT.setEditable(false);
        SAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATActionPerformed(evt);
            }
        });

        SAP.setEditable(false);
        SAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAPActionPerformed(evt);
            }
        });

        Book7.setText("Book");
        Book7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Book1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Book2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FRT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FRP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Book6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TUT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TUP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Book3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(WT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(WP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Book4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(THT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(THP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Book5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SAT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SAP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Book7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book1)
                    .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book2)
                    .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book3)
                    .addComponent(TUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book4)
                    .addComponent(WP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book5)
                    .addComponent(THP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book6)
                    .addComponent(FRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book7))
                .addGap(15, 15, 15)
                .addComponent(jButton8)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STActionPerformed

    private void MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MTActionPerformed

    private void TUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUTActionPerformed

    private void WTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WTActionPerformed

    private void THTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THTActionPerformed

    private void FRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRTActionPerformed

    private void Book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book1ActionPerformed
        // TODO add your handling code here:
        Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Sunday");
            myPreStatObj.setString(4,ST.getText());
            myPreStatObj.setString(5,SP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_Book1ActionPerformed

    private void Book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book2ActionPerformed
        // TODO add your handling code here:
        Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Monday");
            myPreStatObj.setString(4,MT.getText());
            myPreStatObj.setString(5,MP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


                                         

    }//GEN-LAST:event_Book2ActionPerformed

    private void Book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book3ActionPerformed
        // TODO add your handling code here:
        Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Tuseday");
            myPreStatObj.setString(4,TUT.getText());
            myPreStatObj.setString(5,TUP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


                                         

    }//GEN-LAST:event_Book3ActionPerformed

    private void Book4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book4ActionPerformed
       Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Wednesday");
            myPreStatObj.setString(4,WT.getText());
            myPreStatObj.setString(5,WP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


                                         

    }//GEN-LAST:event_Book4ActionPerformed

    private void Book5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book5ActionPerformed
        Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Thrusday");
            myPreStatObj.setString(4,THT.getText());
            myPreStatObj.setString(5,THP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


                                         

    }//GEN-LAST:event_Book5ActionPerformed

    private void Book6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book6ActionPerformed
        Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Friday");
            myPreStatObj.setString(4,FRT.getText());
            myPreStatObj.setString(5,FRP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


                                         

    }//GEN-LAST:event_Book6ActionPerformed

    private void SPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPActionPerformed

    private void MPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPActionPerformed

    private void TUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUPActionPerformed

    private void WPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WPActionPerformed

    private void THPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THPActionPerformed

    private void FRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRPActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Booking_appointement().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void SATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SATActionPerformed

    private void SAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAPActionPerformed

    private void Book7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book7ActionPerformed
        Connection myconObj = null;
        Statement mystatObj = null;
        ResultSet myResObj = null;
        ResultSetMetaData myMeta = null;
        try {

            myconObj = DriverManager.getConnection("jdbc:derby://localhost:1527/JPDataBase", "JP", "JP");

            String Sql = "INSERT INTO JP.RESERVATIONSTABLES (PATIENTID,DOCTORID,APPOINTEMENTDAY,APPOINTEMENTTIME,APPOINTEMENTPLACE,DOCTORFN,DOCTORLN,PATIENTFN,PATIENTLN,PATIENTGENDER,DOCTORSPECIALITY,PATIENTAGE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement myPreStatObj = myconObj.prepareStatement(Sql);
            myPreStatObj.setString(1,patient.getID());
            myPreStatObj.setString(2,doctor.getID());
            myPreStatObj.setString(3,"Saterday");
            myPreStatObj.setString(4,SAT.getText());
            myPreStatObj.setString(5,SAP.getText());
            myPreStatObj.setString(6,doctor.getFirstName());
            myPreStatObj.setString(7,doctor.getLastName());
            myPreStatObj.setString(8,patient.getFirstName());
            myPreStatObj.setString(9,patient.getLastName());
            myPreStatObj.setString(10,patient.getGender());
            myPreStatObj.setString(11,doctor.getSpeciality());
            myPreStatObj.setString(12,patient.getAge());
            
            
            
            
            
            
            
            myPreStatObj.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


                                         

    }//GEN-LAST:event_Book7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book1;
    private javax.swing.JButton Book2;
    private javax.swing.JButton Book3;
    private javax.swing.JButton Book4;
    private javax.swing.JButton Book5;
    private javax.swing.JButton Book6;
    private javax.swing.JButton Book7;
    private javax.swing.JTextField FRP;
    private javax.swing.JTextField FRT;
    private javax.swing.JTextField MP;
    private javax.swing.JTextField MT;
    private javax.swing.JTextField SAP;
    private javax.swing.JTextField SAT;
    private javax.swing.JTextField SP;
    private javax.swing.JTextField ST;
    private javax.swing.JTextField THP;
    private javax.swing.JTextField THT;
    private javax.swing.JTextField TUP;
    private javax.swing.JTextField TUT;
    private javax.swing.JTextField WP;
    private javax.swing.JTextField WT;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
